project:
  type: website
  output-dir: docs

website:
  title: "Junk Data Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: new_resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



